# Site wide configuration

title:            Zain Rizvi's blog
locale:           en_US
url:              https://www.zainrizvi.io
description:      Zain Rizvi's blog. Sharing interesting things I'm learning about Software, Psychology, Self Improvment, and Business

author:
  twitter: zainrzv
  picture: bio-photo.png

# Jekyll configuration
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false

permalink:   /blog/:categories/:title/ #pretty #/:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Zain Rizvi
  avatar: bio-photo.png
  bio: "Software Engineer @ Google, ex-Microsoftie. Experimenter, Life-long Student. Working to improve GCP AI Platform Notebooks. Opinions are all my own"
  email:
  disqus-shortname: zainrizvi
  twitter: zainrzv
  facebook: #username
  google:
    plus: #username
    analytics: UA-63901701-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ZainRizvi
  stackoverflow: 21539/zain-rizvi #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", ".deployment", "Tutorials", "build.bat", "vendor"]
